### ISSUE TITLE
Creating gene annotation from GFF file fails 

### ISSUE THREAD

**Issue by aminakur** [higlass/higlass#1135]
I am trying to create gene annotations file from GFF following this protocol:
https://github.com/higlass/gene_annotations
Receive an error:
```
Processing line #: 0
Traceback (most recent call last):
  File "scripts/gff_to_jsonl.py", line 116, in <module>
    main()
  File "scripts/gff_to_jsonl.py", line 84, in main
    for p in parts["attributes"].strip(";").split(";")
KeyError: 'attributes'
```
Could you please help me with this?

In addition, I cannot find file requirements.txt in the gene_annotations repository. Am I to use requirements.txt file from a different higlass repo?

**Comment by pkerpedjiev** [comment]
Sorry for the delayed response. Would you mind sending the input file and command you used?
