### ISSUE TITLE
higlass for Jupyter not installing

### ISSUE THREAD

**Issue by stalyansky** [higlass/higlass#1155]
_Commit_: 

#### Steps to reproduce
1.
This command is failing for me: `jupyter nbextension install --py --sys-prefix --symlink higlass`
#### Observed behavior
- 
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/jupyter-nbextension", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_core/application.py", line 285, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/traitlets/config/application.py", line 1043, in launch_instance
    app.start()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/notebook/nbextensions.py", line 972, in start
    super().start()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_core/application.py", line 274, in start
    self.subapp.start()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/notebook/nbextensions.py", line 702, in start
    self.install_extensions()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/notebook/nbextensions.py", line 675, in install_extensions
    full_dests = install(self.extra_args[0],
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/notebook/nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/notebook/nbextensions.py", line 1109, in _get_nbextension_metadata
    raise KeyError(
KeyError: 'The Python module higlass is not a valid nbextension, it is missing the `_jupyter_nbextension_paths()` method.'
`
#### Expected behavior
-

**Comment by pkerpedjiev** [comment]
Hey, would you mind posting this issue in the https://github.com/higlass/higlass-python/ repo?

**Comment by stalyansky** [comment]
Thank you, will do
