### ISSUE TITLE
Current develop branch commit cannot be started

### ISSUE THREAD

**Issue by alexpreynolds** [higlass/higlass#1202]
_Commit_: 3f8cd61f8f96600363c864ff9c8de5f5c9ed1ba4

#### Steps to reproduce
1. Pull `develop` branch
2. Run `npm install` and `npm run start`

#### Observed behavior
- I get the following error:

```
  VITE v5.4.11  ready in 331 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
✘ [ERROR] Missing "./lib/utils" specifier in "cheerio" package [plugin vite:dep-pre-bundle]

    node_modules/enzyme/build/Utils.js:84:21:
      84 │ var _utils = require('cheerio/lib/utils');
         ╵                      ~~~~~~~~~~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/vite/node_modules/esbuild/lib/main.js:1150:20:
      1150 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/areynolds/Developer/Github/higlass/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46934:13)
    at handlePlugins (/Users/areynolds/Developer/Github/higlass/node_modules/vite/node_modules/esbuild/lib/main.js:1150:21)
    at buildOrContextImpl (/Users/areynolds/Developer/Github/higlass/node_modules/vite/node_modules/esbuild/lib/main.js:873:5)
    at Object.buildOrContext (/Users/areynolds/Developer/Github/higlass/node_modules/vite/node_modules/esbuild/lib/main.js:699:5)
    at /Users/areynolds/Developer/Github/higlass/node_modules/vite/node_modules/esbuild/lib/main.js:2032:68
    at new Promise (<anonymous>)
    at Object.context (/Users/areynolds/Developer/Github/higlass/node_modules/vite/node_modules/esbuild/lib/main.js:2032:27)
    at Object.context (/Users/areynolds/Developer/Github/higlass/node_modules/vite/node_modules/esbuild/lib/main.js:1874:58)
    at prepareEsbuildOptimizerRun (file:///Users/areynolds/Developer/Github/higlass/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:50924:33)
```

Opening http://localhost:5173 raises further exceptions/errors.

#### Expected behavior
- I'd expect to see the usual test site

**Comment by alexpreynolds** [comment]
I found a fix, but it may not be necessary. I'll close this and the other issue up for now.

**Comment by pkerpedjiev** [comment]
What was your fix?
