### ISSUE TITLE
Current v1.13.4 tag distribution cannot be started

### ISSUE THREAD

**Issue by alexpreynolds** [higlass/higlass#1203]
This issue appears to be identical or related to a previous issue (https://github.com/higlass/higlass/issues/1202).

_Commit_: 85813c552b5cee09935246f0f06020e995e6faac

#### Steps to reproduce
1. Checkout or clone v1.13.4-tagged higlass, e.g. `git checkout -b test-1p13p4 v1.13.4`
2. Install packages: `npm install` or `npm clean-install`
3. Start the project: `npm run start`

#### Observed behavior
- I see the following error:

```
  VITE v5.4.11  ready in 300 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
✘ [ERROR] Missing "./lib/utils" specifier in "cheerio" package [plugin vite:dep-pre-bundle]

    node_modules/enzyme/build/Utils.js:84:21:
      84 │ var _utils = require('cheerio/lib/utils');
         ╵                      ~~~~~~~~~~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/vite/node_modules/esbuild/lib/main.js:1150:20:
      1150 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/areynolds/Developer/Github/higlass/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46934:13)
    at handlePlugins (/Users/areynolds/Developer/Github/higlass/node_modules/vite/node_modules/esbuild/lib/main.js:1150:21)
    at buildOrContextImpl (/Users/areynolds/Developer/Github/higlass/node_modules/vite/node_modules/esbuild/lib/main.js:873:5)
    at Object.buildOrContext (/Users/areynolds/Developer/Github/higlass/node_modules/vite/node_modules/esbuild/lib/main.js:699:5)
    at /Users/areynolds/Developer/Github/higlass/node_modules/vite/node_modules/esbuild/lib/main.js:2032:68
    at new Promise (<anonymous>)
    at Object.context (/Users/areynolds/Developer/Github/higlass/node_modules/vite/node_modules/esbuild/lib/main.js:2032:27)
    at Object.context (/Users/areynolds/Developer/Github/higlass/node_modules/vite/node_modules/esbuild/lib/main.js:1874:58)
    at prepareEsbuildOptimizerRun (file:///Users/areynolds/Developer/Github/higlass/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:50924:33)
```

Additional errors and exceptions are displayed when viewing http://localhost:5173

#### Expected behavior
- I would expect to see the usual HiGlass site

**Comment by alexpreynolds** [comment]
I found a fix, but it may not be necessary. I'll close this and the other issue up for now.
