### ISSUE TITLE
Flakey tests on Travis?

### ISSUE THREAD

**Issue by mccalluc** [higlass/higlass#335]
On these travis builds:

- https://travis-ci.org/higlass/higlass/builds/446711229
- https://travis-ci.org/higlass/higlass/builds/446310460
- https://travis-ci.org/higlass/higlass/builds/445781811

we got:

```
Chromium 62.0.3202 (Ubuntu 0.0.0) Simple HiGlassComponent Viewport projection tests Ensure that the viewport projection's borders are black FAILED
	AssertionError: expected 'rgb(119, 119, 119)' to deeply equal 'rgb(0, 0, 0)'
	    at UserContext.<anonymous> (test/ViewportProjectionTests.js:92935:56)
```

and on:

- https://travis-ci.org/higlass/higlass/builds/446396089
- https://travis-ci.org/higlass/higlass/builds/446425262

we got:

```
Chromium 62.0.3202 (Ubuntu 0.0.0) Simple HiGlassComponent View config buttons Cleans up previously created instances and mounts a new component FAILED
	Error: 
	      Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none.
	      To configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`
	      before using any of Enzyme's top level APIs, where `Adapter` is the adapter
	      corresponding to the library currently being tested. For example:
	      import Adapter from 'enzyme-adapter-react-15';
	      To find out more about this, see http://airbnb.io/enzyme/docs/installation/index.html
	    
	    at validateAdapter (test/HiGlassComponentTest.jsx:37680:11)
	    at getAdapter (test/HiGlassComponentTest.jsx:36979:36)
	    at new ReactWrapper (test/HiGlassComponentTest.jsx:32722:49)
	    at mount (test/HiGlassComponentTest.jsx:37065:10)
	    at UserContext.<anonymous> (test/HiGlassComponentTest.jsx:91981:31)
	    
Chromium 62.0.3202 (Ubuntu 0.0.0) Simple HiGlassComponent View config buttons Disables the add track button on the first view FAILED
	TypeError: Cannot read property 'setProps' of null
	    at UserContext.<anonymous> (test/HiGlassComponentTest.jsx:91999:11)
```

**Comment by pkerpedjiev** [comment]
Yup, those two are known to fail. Second one I fixed by removing the obsolete `HiGlassComponentTest.jsx`. First one should be fixed shortly.

**Comment by mccalluc** [comment]
New one (not sure whether you'd like a separate issue for each failure, or one master issue that gets updated.) https://travis-ci.org/higlass/higlass/builds/447986504#L3280

```
Chromium 62.0.3202 (Ubuntu 0.0.0) Simple HiGlassComponent Viewport projection tests Dispatches a mousewheel event on the viewport projection and makes sure it zooms FAILED
	AssertionError: expected 769359664.1270934 to not deeply equal 769359664.1270934
	    at test/ViewportProjectionTests.js:93841:43
	    at waitForTransitionsFinished (test/ViewportProjectionTests.js:142529:5)
	    at UserContext.<anonymous> (test/ViewportProjectionTests.js:93837:45)
```

**Comment by pkerpedjiev** [comment]
No, I'm aware of them. That one I've been sort of stumped on because there's some other error messages but I'll continue trying to figure it out.
