### ISSUE TITLE
Is except-parens the best fix for no-return-assign?

### ISSUE THREAD

**Issue by mccalluc** [higlass/higlass#480]
These could be fixed by enclosing the assignment in parens, and that is the default behavior. https://eslint.org/docs/rules/no-return-assign#except-parens

I could do that, and it would prevent the casual typo, but it still feels a little sneaky to take the return value from an assignment... but changing all of these to long functions adds a lot of clutter. Thoughts? Indicate what direction you'd prefer, and I'll implement.

`$ ./node_modules/eslint/bin/eslint.js --ignore-path .eslintignore-minimal --config .eslintrc-minimal --quiet --format codeframe app/scripts/ test/`

<details>

```
error: Arrow function should not return assignment (no-return-assign) at app/scripts/Autocomplete.js:326:16:
  324 |         <input
  325 |           {...inputProps}
> 326 |           ref={el => this.inputEl = el}
      |                ^
  327 |           aria-autocomplete="list"
  328 |           autoComplete="off"
  329 |           onBlur={this.composeEventHandlers(


error: Arrow function should not return assignment (no-return-assign) at app/scripts/ConfigTrackMenu.js:36:14:
  34 |     return (
  35 |       <div
> 36 |         ref={c => this.div = c}
     |              ^
  37 |         data-menu-type="ConfigTrackMenu"
  38 |         style={{
  39 |           left: this.state.left,


error: Arrow function should not return assignment (no-return-assign) at app/scripts/ContextMenuContainer.js:190:14:
  188 |     return (
  189 |       <div
> 190 |         ref={c => this.div = c}
      |              ^
  191 |         className="context-menu-item"
  192 |         style={wholeStyle}
  193 |         styleName={stylenames}


error: Arrow function should not return assignment (no-return-assign) at app/scripts/GenomePositionSearchBox.js:700:14:
  698 |     return (
  699 |       <FormGroup
> 700 |         ref={c => this.gpsbForm = c}
      |              ^
  701 |         bsSize="small"
  702 |         styleName={className}
  703 |       >


error: Arrow function should not return assignment (no-return-assign) at app/scripts/GenomePositionSearchBox.js:705:16:
  703 |       >
  704 |         <DropdownButton
> 705 |           ref={c => this.assemblyPickButton = c}
      |                ^
  706 |           bsSize="small"
  707 |           className={styles['genome-position-search-bar-button']}
  708 |           id={this.uid}


error: Arrow function should not return assignment (no-return-assign) at app/scripts/GenomePositionSearchBox.js:716:16:
  714 | 
  715 |         <Autocomplete
> 716 |           ref={c => this.autocompleteMenu = c}
      |                ^
  717 |           getItemValue={item => item.geneName}
  718 |           inputProps={{
  719 |             className: styles['genome-position-search-bar'],


error: Arrow function should not return assignment (no-return-assign) at app/scripts/ListWrapper.js:67:14:
  65 |         {...this.props}
  66 |         {...props}
> 67 |         ref={element => this.ref = element}
     |              ^
  68 |       />
  69 |     );
  70 |   }


error: Arrow function should not return assignment (no-return-assign) at app/scripts/NestedContextMenu.js:83:14:
  81 |     return (
  82 |       <div
> 83 |         ref={c => this.div = c}
     |              ^
  84 |         style={{
  85 |           left: this.state.left,
  86 |           top: this.state.top,


error: Arrow function should not return assignment (no-return-assign) at app/scripts/SeriesOptions.js:45:16:
  43 |       >
  44 |         <Checkbox
> 45 |           ref={c => this.normalizeCheckbox = c}
     |                ^
  46 |           onChange={this.handleNormalizeCheckboxChanged.bind(this)}
  47 |         >
  48 |                     Normalize By


9 errors found.
```

</details>

**Comment by mccalluc** [comment]
In the TODOs in .eslintrc. That's enough of a reminder, if we ever want to do this.
