### ISSUE TITLE
local error

### ISSUE THREAD

**Issue by hzaumsq** [higlass/higlass#594]
#####C:\Users\msq\temp1> docker exec higlass-container python higlass-server/manage.py ingest_tileset --filename .\50k_output.cool --filetype cooler --datatype matrix
uid: YG6qIG1WS8iMmff_j3E2Ag
Traceback (most recent call last):
File "higlass-server/manage.py", line 22, in 
execute_from_command_line(sys.argv)
File "/opt/conda/lib/python3.6/site-packages/django/core/management/init.py", line 371, in execute_from_command_line
utility.execute()
File "/opt/conda/lib/python3.6/site-packages/django/core/management/init.py", line 365, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/opt/conda/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
self.execute(*args, **cmd_options)
File "/opt/conda/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
output = self.handle(*args, **options)
File "/home/higlass/projects/higlass-server/tilesets/management/commands/ingest_tileset.py", line 52, in handle
django_file = File(open(filename, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '.\50k_output.cool'

C:\Users\msq\temp1> ls
目录: C:\Users\msq\temp1
Mode LastWriteTime Length Name

-a---- 2019/3/22 9:07 3808854 50k_output.cool
-a---- 2019/3/22 22:59 0 nginx-stderr---supervisor-HCMZTI.log
-a---- 2019/3/22 22:59 0 nginx-stdout---supervisor-RjNur2.log
-a---- 2019/3/22 23:42 10306 uwsgi-stderr---supervisor-IiVarm.log
-a---- 2019/3/22 23:00 1168 uwsgi-stdout---supervisor-w6z1vS.log

####C:\Users\msq\temp1> docker exec higlass-container python higlass-server/manage.py ingest_tileset --filename 50k_output.cool --filetype cooler --datatype matrix
uid: DkZln6pXTyaDuevA5T-iaw
Traceback (most recent call last):
File "higlass-server/manage.py", line 22, in 
execute_from_command_line(sys.argv)
File "/opt/conda/lib/python3.6/site-packages/django/core/management/init.py", line 371, in execute_from_command_line
utility.execute()
File "/opt/conda/lib/python3.6/site-packages/django/core/management/init.py", line 365, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/opt/conda/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
self.execute(*args, **cmd_options)
File "/opt/conda/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
output = self.handle(*args, **options)
File "/home/higlass/projects/higlass-server/tilesets/management/commands/ingest_tileset.py", line 52, in handle
django_file = File(open(filename, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '50k_output.cool'

Why it says there is no such file?I'm confused.

**Comment by pkerpedjiev** [comment]
Docker has its own internal filesystem. When you run the `manage.py ingest_tileset.py` command in the Docker container, it looks for the 50k_output.cool file in its own filesystem. That file, however, is not there. It's on your computer's filesystem. To use it from within Docker, you have to mount your local directory within docker. You can do that with the `-v` option:

```
docker exec -v C:\Users\msq\temp1:/tmp higlass-container python higlass-server/manage.py ingest_tileset --filename /tmp/50k_output.cool --filetype cooler --datatype matrix
```

This will mount your local directory (`C:\Users\msq\temp1`) as `/tmp` within the Docker container. You then ingest the file from there.
