### ISSUE TITLE
hgflask.client or higlass.client  when working in Jupyter notebook ?

### ISSUE THREAD

**Issue by jakevc** [higlass/higlass#616]
_Commit_: 

#### Steps to reproduce
1.

I don't understand if I should be importing higlass.client or hgflask.client, the docs show both and higlass.client throws flask error. 

```
import higlass
import higlass.client as hgc
view1 = hgc.View([
    hgc.Track(track_type='top-axis', position='top'),
    hgc.Track(track_type='heatmap', position='center',
             tileset_uuid='CQMd6V_cRw6iCI_-Unl3PQ',
              server="http://higlass.io/api/v1/",
              height=250,
             options={ 'valueScaleMax': 0.5 }),
])
(display, server, viewconf) = higlass.display([view1])
display
import higlass
import higlass.client as hgc
view1 = hgc.View([
    hgc.Track(track_type='top-axis', position='top'),
    hgc.Track(track_type='heatmap', position='center',
             tileset_uuid='CQMd6V_cRw6iCI_-Unl3PQ',
              server="http://higlass.io/api/v1/",
              height=250,
             options={ 'valueScaleMax': 0.5 }),
])
(display, server, viewconf) = higlass.display([view1])
display
```

#### Observed behavior
- 
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-24-d44aa4ca60c5> in <module>
      9              options={ 'valueScaleMax': 0.5 }),
     10 ])
---> 11 (display, server, viewconf) = higlass.display([view1])
     12 display

/home/groups/hoolock/u1/jvc/miniconda3/envs/higlass/lib/python3.7/site-packages/higlass/viewer.py in display(views, location_sync, zoom_sync, server_port)
      6     Instantiate a HiGlass display with the given views
      7     '''
----> 8     from .server import Server
      9     from .client import ViewConf
     10     tilesets = []

/home/groups/hoolock/u1/jvc/miniconda3/envs/higlass/lib/python3.7/site-packages/higlass/server.py in <module>
     13 
     14 # from flask_restful import reqparse, abort, Api, Resource
---> 15 from flask_cors import CORS
     16 
     17 from fuse import FUSE

ModuleNotFoundError: No module named 'flask_cors'
```

#### Expected behavior
- https://github.com/higlass/higlass/blob/develop/docs/jupyter.rst

**Comment by pkerpedjiev** [comment]
Hey, should be `higlass.client`. That's a typo in the docs that we overlooked. It'll be fixed in the next docs release.

Your error is likely because we neglected to add `flask-cors` to the requirements. Can you try doing `pip install -U flask-cors` and then running your code again?

**Comment by jakevc** [comment]
Okay great. Also, should this repo be disregarded then? https://github.com/higlass/higlass-jupyter 

After installing flask-cors, and re-running the same chunk i get:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-36-6b1223a16fc1> in <module>
      9              options={ 'valueScaleMax': 0.5 }),
     10 ])
---> 11 (display, server, viewconf) = higlass.display([view1])
     12 display
     13 import higlass

/home/groups/hoolock/u1/jvc/miniconda3/envs/higlass/lib/python3.7/site-packages/higlass/viewer.py in display(views, location_sync, zoom_sync, server_port)
      6     Instantiate a HiGlass display with the given views
      7     '''
----> 8     from .server import Server
      9     from .client import ViewConf
     10     tilesets = []

/home/groups/hoolock/u1/jvc/miniconda3/envs/higlass/lib/python3.7/site-packages/higlass/server.py in <module>
     15 from flask_cors import CORS
     16 
---> 17 from fuse import FUSE
     18 import requests
     19 import slugid

ModuleNotFoundError: No module named 'fuse'
```

**Comment by pkerpedjiev** [comment]
Yes, use `higlass-python`.

The `fuse` issue is because you need to install `fusepy`. Check out the requirements.txt here: `https://github.com/higlass/higlass-python/blob/master/requirements.txt` and just install everything there.

Sorry about those issues and thanks for reporting. That package is still really new and we're still ironing out all those bugs and installation requirements.

**Comment by jakevc** [comment]
Okay great thanks! So now I've got some action, but it's not quite displaying the HiGlassDisplay, and there are some warnings:

```
self.diskcache_directory /tmp/higlass-python/dc True
starting fuse
Process Process-1:
Traceback (most recent call last):
  File "/home/groups/hoolock/u1/jvc/miniconda3/envs/higlass/lib/python3.7/site-packages/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/home/groups/hoolock/u1/jvc/miniconda3/envs/higlass/lib/python3.7/site-packages/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/groups/hoolock/u1/jvc/miniconda3/envs/higlass/lib/python3.7/site-packages/higlass/server.py", line 281, in start_fuse
    foreground=False,
  File "/home/groups/hoolock/u1/jvc/miniconda3/envs/higlass/lib/python3.7/site-packages/fuse.py", line 711, in __init__
    raise RuntimeError(err)
RuntimeError: 1
self.diskcache_directory /tmp/hgflask/dc True
starting fuse
Process Process-2:
Traceback (most recent call last):
  File "/home/groups/hoolock/u1/jvc/miniconda3/envs/higlass/lib/python3.7/site-packages/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/home/groups/hoolock/u1/jvc/miniconda3/envs/higlass/lib/python3.7/site-packages/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/groups/hoolock/u1/jvc/miniconda3/envs/higlass/lib/python3.7/site-packages/higlass/server.py", line 281, in start_fuse
    foreground=False,
  File "/home/groups/hoolock/u1/jvc/miniconda3/envs/higlass/lib/python3.7/site-packages/fuse.py", line 711, in __init__
    raise RuntimeError(err)
RuntimeError: 1
 * Serving Flask app "higlass.server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
self.diskcache_directory /tmp/hgflask/dc True
starting fuse
Process Process-4:
Traceback (most recent call last):
  File "/home/groups/hoolock/u1/jvc/miniconda3/envs/higlass/lib/python3.7/site-packages/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/home/groups/hoolock/u1/jvc/miniconda3/envs/higlass/lib/python3.7/site-packages/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/groups/hoolock/u1/jvc/miniconda3/envs/higlass/lib/python3.7/site-packages/higlass/server.py", line 281, in start_fuse
    foreground=False,
  File "/home/groups/hoolock/u1/jvc/miniconda3/envs/higlass/lib/python3.7/site-packages/fuse.py", line 711, in __init__
    raise RuntimeError(err)
RuntimeError: 1
terminating: F8zPKgTFT1CeX9s-rWKSlQ
 * Serving Flask app "higlass.server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
HiGlassDisplay(viewconf={'editable': True, 'views': [{'uid': 'WRftVwOEQkq86l3RBGq5ag', 'tracks': {'top': [{'ty…
```

**Comment by pkerpedjiev** [comment]
OK, cool. What OS are you using?

Could you also pop open your browser's console and paste the contents? I suspect that you don't FUSE enabled in your OS but even if you don't that shouldn't be a problem and we can run around it.

**Comment by jakevc** [comment]
Sorry about late response. The problem I think, is related to how I was running in a jupyter hub, and needed some extra js plugings enabled. I am able to work it from a locally running jupyter notebook.

**Comment by jakevc** [comment]
That was my workaround to trying to get higlass loading data from a public URL, which I have not yet has success with. #434
