### ISSUE TITLE
Load Juicer text file into HiGlass

### ISSUE THREAD

**Issue by rahmas36** [higlass/higlass#778]
Hi everyone. I am a wet lab postdoc at the Icahn School of Medicine. I am generating HiC data from human brain. I am quite new to computational biology. I have been able to run HiGlass through docker and am now browsing my HiC datasets. My colleague generated Juicer text files of loops. How do I convert these files into a format that can be ingested into HiGlass and visualized?

**Comment by nvictus** [comment]
Hi @rahmas36! You shoud be able to aggregate them into an ingestible form using the [clodius](https://github.com/higlass/clodius) package as described here: https://docs.higlass.io/data_preparation.html#bedpe-like-files.

**Comment by rahmas36** [comment]
Thanks @nvictus 

I have clodius installed and have previously aggregated BED files for 1D tracks. When I run clodius to aggregate the Juicer txt file, I get errors:

c02v50nrj1g5:downloads samirrahman$ clodius aggregate bedpe \
> --assembly hg38 \
> --chr1-col 1 --from1-col 2 --to1-col 3 \
> --chr2-col 4 --from2-col 5 --to2-col 6 \
> --output-file Ndomains.txt.multires \
> --has-header juicer_multiple_res_N.txt
output_file: Ndomains.txt.multires
plain
Traceback (most recent call last):
  File "/Users/samirrahman/anaconda3/lib/python3.7/site-packages/clodius/cli/aggregate.py", line 200, in line_to_dict
    parts[chr1_col - 1]] + int(parts[from1_col - 1]),
KeyError: '9'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/samirrahman/anaconda3/bin/clodius", line 10, in <module>
    sys.exit(cli())
  File "/Users/samirrahman/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/samirrahman/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/samirrahman/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/samirrahman/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/samirrahman/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/samirrahman/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/samirrahman/anaconda3/lib/python3.7/site-packages/clodius/cli/aggregate.py", line 1530, in bedpe
    chr2_col=chr2_col, from2_col=from2_col, to2_col=to2_col
  File "/Users/samirrahman/anaconda3/lib/python3.7/site-packages/clodius/cli/aggregate.py", line 271, in _bedpe
    for line in [line.strip() for line in f] if line]
  File "/Users/samirrahman/anaconda3/lib/python3.7/site-packages/clodius/cli/aggregate.py", line 271, in <listcomp>
    for line in [line.strip() for line in f] if line]
  File "/Users/samirrahman/anaconda3/lib/python3.7/site-packages/clodius/cli/aggregate.py", line 221, in line_to_dict
    raise(KeyError(error_str))
KeyError: "ERROR converting chromosome position to genome position. Please make sure you've specified the correct assembly using the --assembly option or a chromsizes file using the . --chromsizes-filename option.Current assembly: hg38, chromosomes: 9,9"

**Comment by rahmas36** [comment]
Hi, I was able to solve the issue. I had to add "chr" for every row for the two sets of coordinates in order to format the file into a proper bedpe-like file. I was able to aggregate and ingest into HiGlass. Thanks @nvictus for your advice!

**Comment by nvictus** [comment]
Glad you solved it!
