### ISSUE TITLE
install higlass

### ISSUE THREAD

**Issue by BenxiaHu** [higlass/higlass#906]
Hi,
   I first installed Docker, and installed Anaconda3 in Win10. I try to install HiGlass in the conda using `pip install higlass-manage`. But I got this error:
Using cached pysam-0.15.4.tar.gz (1.6 MB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Conda\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\
\huben\\AppData\\Local\\Temp\\pip-install-c68ki7qc\\pysam\\setup.py'"'"'; __file__='"'"'C:\\Users\\hube
n\\AppData\\Local\\Temp\\pip-install-c68ki7qc\\pysam\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"',
 open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __fil
e__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\huben\AppData\Local\Temp\pip-install-c68ki7qc\pysa
m\pip-egg-info'
         cwd: C:\Users\huben\AppData\Local\Temp\pip-install-c68ki7qc\pysam\
    Complete output (23 lines):
    # pysam: cython is available - using cythonize if necessary
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\huben\AppData\Local\Temp\pip-install-c68ki7qc\pysam\setup.py", line 241, in <modul
e>
        htslib_make_options = run_make_print_config()
      File "C:\Users\huben\AppData\Local\Temp\pip-install-c68ki7qc\pysam\setup.py", line 68, in run_mak
e_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "D:\Conda\lib\subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "D:\Conda\lib\subprocess.py", line 488, in run
        with Popen(*popenargs, **kwargs) as process:
      File "D:\Conda\lib\subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "D:\Conda\lib\subprocess.py", line 1207, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] \u7cfb\u7edf\u627e\u4e0d\u5230\u6307\u5b9a\u7684\u6587\u4ef6\u3002
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command
 output.

Then I installed pysam in the win10, but I still got the same error.
Do you know how to resolve this error?
Best,

**Comment by pkerpedjiev** [comment]
Maybe try `conda install -c bioconda pysam` and then try higlass-manage?

If that doesn't work, you can just start the Docker container directly without `higlass-manage`. Take a look here: https://docs.higlass.io/higlass_docker.html#running-locally (substitute the latest Docker version, v0.6.47)

**Comment by benxiahu** [comment]
Hi,
   Thanks. Now I can start the Docker. But I still have several questions:
   --publish -------what does it mean and how to define it?
   --volume -------what does it mean and how to define it?
   --volume -------what does it mean and how to define it?
the format of input file is .txt, do I need to convert it into .cool?

**Comment by sunilnahata** [comment]
I don't think `pysam` for Windows OS exists at the moment @pkerpedjiev 
I had similar issues earlier and this post answered my question [https://stackoverflow.com/a/60199392/12587441]. A workaround was to get the WSL working and use HiGlass from the docker container.

**Comment by sunilnahata** [comment]
I don't think pysam for Windows OS exists at the moment @pkerpedjiev 
I had similar issues earlier and this post answered my question [](https://stackoverflow.com/a/60199392/12587441). A workaround was to get the WSL working on Windows 10 and install Linux and use HiGlass from the docker container.

**Comment by sunilnahata** [comment]
I don't think pysam for Windows OS exists at the moment @pkerpedjiev
I had similar issues earlier and this post answered my question [https://stackoverflow.com/a/60199392/12587441](url). A workaround was to get the WSL working on Windows 10 and install Linux and use HiGlass from the docker container.
